config/routes.rb
Rails.application.routes.draw do
  resources :feeds do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :albums, only: [:new, :create, :show]
  root to: "sessions#new"
end

app/models/album.rb
class Album < ApplicationRecord
  before_validation { email.downcase! }
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true, length: { maximum: 55 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  has_secure_password
  validates :password, presence: true, length: { minimum: 5, maximum: 16 }
  has_many :feeds
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :album
  validates :content, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_path(@album.id)
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  private
  def album_params
    params.require(:album).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy,]

  def index
    @feeds = Feed.all
  end

  def new
    if params[:back]
      @feed = Feed.new(feed_params)
    else
      @feed = Feed.new
    end
  end

  def create
  @feed = current_album.feeds.build(feed_params)
  respond_to do |format|
    if @feed.save
      format.html { redirect_to @feed, notice: '正しく行われました' }
    else
      format.html { render :new }
    end
   end
  end

  def show
  end

  def edit
  end

  def confirm
    @feed = current_album.feeds.build(feed_params)
    render :new if @feed.invalid?
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'アップデートされました' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: '正しく削除されました' }
    end
  end

  private
  def set_feed
    @feed = Feed.find(params[:id])
  end

  def feed_params
    params.require(:feed).permit(:image, :image_cache, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    album = Album.find_by(email: params[:session][:email].downcase)
    if album && album.authenticate(params[:session][:password])
      session[:album_id] = album.id
      redirect_to album_path(album.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:album_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == "create"
      confirm_feeds_path
    elsif action_name == 'edit'
      feed_path
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_album
    @current_album ||= Album.find_by(id: session[:album_id])
  end
  def logged_in?
    current_album.present?
  end
end

app/views/albums/new.html.erb
<div class="album_new_body">
<br><br><h1>ユーザー登録</h1><br>
<% if @album.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@album.errors.count, "error") %> <%= @album.name %> エラーが発生しました:</h2>
    <ul>
    <% @album.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @album, local: true) do |f| %>
<table class="album_new_table">
  <tr>
  <th><%= f.label :name, "名前" %></th>
  <th><%= f.text_field :name %></th>
  </tr>
<tr>
  <th><%= f.label :email, "メールアドレス" %></th>
  <th><%= f.email_field :email %></th>
</tr>
<tr>
  <th><%= f.label :password, "パスワード" %></th>
  <th><%= f.password_field :password %></th>
</tr>
<tr>
  <th><%= f.label :password_confirmation, "確認用パスワード" %></th>
  <th><%= f.password_field :password_confirmation %></th>
</tr>
<tr>
  <th></th>
  <th id= "make_account" ><%= f.submit "アカウントを作成" %></th>
  </tr>
<% end %>
</table>
</div>

app/views/albums/show.html.erb
<show class="profile_body">
<table class="profile_table">
<br><br><br><br>
<tr>
  <th class="profile_th" colspan="2" >&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspプロフィール</th>
</tr>
<tr>
  <th class="profile_th">名前:</th>
  <th class="profile_th"><%= @album.name %></th>
</tr>
<tr>
  <th class="profile_th">メールアドレス:</th>
  <th class="profile_th"><%= @album.email %></th>
</tr>
</table>
<div class="profile_button">
  <button class="profile_button"><%= link_to '投稿一覧へ', feeds_path %></button>
  <button class="profile_button"><%= link_to '投稿する', new_feed_path %></button>
</div>
</show>

app/views/feeds/_form.html.erb
<div class="feed_form_body">
  <%= form_with(model: @feed, local: true ,url: choose_new_or_edit ) do |form| %>
    <% if feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feed.errors.count, "error") %> エラーが発生しました:</h2>
      <ul>
        <% feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      </div>
  <% end %>

  <div class="field">
    <p class="feed_form_posted">
      <%= (form.label :image, "現在の画像：") if @feed.image && @feed.image.url %>
      <%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %></p>
    <p class="feed_form_posted">
      <%= (form.label :content, "現在の内容：") if @feed.content %>
      <%= @feed.content %></p>
    <h3 class="feed_form_h3">新規投稿:画像とコメントをお願いします。</h3>
    <div class="feed_form_posting">
      <%= form.file_field :image %>
      <%= form.hidden_field :image_cache %>
    <p class="feed_form_posting">
      <%= form.label :content, "投稿内容:" %>
      <%= form.text_field :content %></p>
    <p><%= form.submit %></p>
    <% end %>
  </div>
</div>

app/views/feeds/confirm.html.erb
<br><br><h1>確認画面</h1><br>
<%= form_with(model: @feed, local: true) do |form| %>
　　<%= image_tag(@feed.image.url) if @feed.image && @feed.image.url %>
　　<%= form.hidden_field :image_cache %>
　　<%= form.hidden_field :content %>
　　<p>投稿内容:<%= @feed.content %></p>
　　<%= form.submit "投稿する" %>
<% end %>
    <%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/feeds/edit.html.erb
<br><br><h1>編集ページ</h1><br>
<%= render 'form', feed: @feed %><br><br><br>
<button class= "feeds_edit_button" ><%= link_to '詳細', @feed %></button>
<button class= "feeds_edit_button"><%= link_to '一覧', feeds_path %></button>

app/views/feeds/index.html.erb
<br><br><br><h1 class="feed_index_h1">投稿内容一覧</h1><br>
<table class="feed_index_table">
    <tr>
    <th class="feed_index_th">投稿者</th>
    <th class="feed_index_th">投稿内容</th>
    <th class="feed_index_th">投稿画像</th>
  </tr>
    <% @feeds.each do |feed| %>
  <tr>
    <td class="feed_index_td" ><%= feed.album.name %></td>
    <td class="feed_index_td" ><%= feed.content %></td>
    <td class="feed_index_td" ><%= image_tag(feed.image.url) if feed.image.url %></td>
    <td><button class="feed_index_button" ><%= link_to '詳細', feed %></button></td>
    <td><button class="feed_index_button" ><%= link_to '編集', edit_feed_path(feed) %></button></td>
    <td><button class="feed_index_button" ><%= link_to '削除', feed, method: :delete, data: { confirm: '削除しますか？' } %></button></td>
  </tr>
    <% end %>
</table><br>
<button class= "feed_index_button2" ><%= link_to '投稿する', new_feed_path %></button>

app/views/feeds/new.html.erb
<br><br><h1>投稿内容確認</h1><br>
<%= render 'form', feed: @feed %><br><br><br>
<br><br><br><button><%= link_to '一覧へ戻る', feeds_path %></button>

app/views/feeds/show.html.erb
<br><br><h1 class="feed_show_h1">投稿の詳細</h1><br>
<table class="feed_show_table">
  <tr>
    <th class="feed_show_th">投稿者</th>
    <th class="feed_show_th">投稿内容</th>
    <th class="feed_show_th">投稿画像</th>
  </tr>
  <tr>
    <td class="feed_show_td" ><%= @feed.album.name %></td>
    <td class="feed_show_td" ><%= @feed.content %></td>
    <td class="feed_show_td" ><%= image_tag(@feed.image.url) if @feed.image.present? %></td>
  </tr>
</table>
<div class="feed_show_bottun">
  <button><%= link_to '編集', edit_feed_path(@feed) %></button>
  <button><%= link_to '一覧', feeds_path %></button>
  <button><%= link_to '投稿する', new_feed_path %></button>
</div>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Facebook clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  　<body>
    <header>
      <div class="application_div">
        <% flash.each do |key, value| %>
          <%= content_tag(:div, value, class: "#{key}") %>
        　<% end %>
        　<% if logged_in? %>
          <button class="application_button"><%= link_to "プロフィール", album_path(current_album.id) %></button>
          <button class="application_button"><%= link_to "ユーザーログアウト", session_path(current_album.id), method: :delete %></button>
        　<% else %>
          <button class="application_button"><%= link_to "サインアップ", new_album_path %></button>
          <button class="application_button"><%= link_to "ユーザーログイン", new_session_path %></button>
          <% end %>
          <%= yield %>
      </div>
    </header>
　　</body>
<footer>
  <p>©Facebook clone</p>
</footer>
</html>